# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registryServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14registryServer.proto\x12\x03rpc\"\'\n\x06Server\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x13\n\x11serverListRequest\"&\n\x08Response\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"\x7f\n\x12serverListResponse\x12<\n\rserverDetails\x18\x01 \x03(\x0b\x32%.rpc.serverListResponse.ServerDetails\x1a+\n\rServerDetails\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t2~\n\x0eRegistryServer\x12(\n\x08Register\x12\x0b.rpc.Server\x1a\r.rpc.Response\"\x00\x12\x42\n\rGetServerList\x12\x16.rpc.serverListRequest\x1a\x17.rpc.serverListResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registryServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVER._serialized_start=29
  _SERVER._serialized_end=68
  _SERVERLISTREQUEST._serialized_start=70
  _SERVERLISTREQUEST._serialized_end=89
  _RESPONSE._serialized_start=91
  _RESPONSE._serialized_end=129
  _SERVERLISTRESPONSE._serialized_start=131
  _SERVERLISTRESPONSE._serialized_end=258
  _SERVERLISTRESPONSE_SERVERDETAILS._serialized_start=215
  _SERVERLISTRESPONSE_SERVERDETAILS._serialized_end=258
  _REGISTRYSERVER._serialized_start=260
  _REGISTRYSERVER._serialized_end=386
# @@protoc_insertion_point(module_scope)
