# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x05proto\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"P\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\";\n\x0cWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"@\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"(\n\nserverData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"$\n\x12serverDataResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"6\n\x13\x44\x65leteRequestServer\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"T\n\x12WriteRequestServer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2\xa1\x03\n\x06Server\x12\x31\n\x04read\x12\x12.proto.ReadRequest\x1a\x13.proto.ReadResponse\"\x00\x12\x41\n\x12writeClientRequest\x12\x13.proto.WriteRequest\x1a\x14.proto.WriteResponse\"\x00\x12G\n\x12writeServerRequest\x12\x19.proto.WriteRequestServer\x1a\x14.proto.WriteResponse\"\x00\x12J\n\x13\x64\x65leteServerRequest\x12\x1a.proto.DeleteRequestServer\x1a\x15.proto.DeleteResponse\"\x00\x12\x44\n\x13\x64\x65leteClientRequest\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponse\"\x00\x12\x46\n\x14\x61\x64\x64NonPrimaryServers\x12\x11.proto.serverData\x1a\x19.proto.serverDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READREQUEST._serialized_start=23
  _READREQUEST._serialized_end=50
  _READRESPONSE._serialized_start=52
  _READRESPONSE._serialized_end=132
  _WRITEREQUEST._serialized_start=134
  _WRITEREQUEST._serialized_end=193
  _WRITERESPONSE._serialized_start=195
  _WRITERESPONSE._serialized_end=259
  _SERVERDATA._serialized_start=261
  _SERVERDATA._serialized_end=301
  _SERVERDATARESPONSE._serialized_start=303
  _SERVERDATARESPONSE._serialized_end=339
  _DELETEREQUESTSERVER._serialized_start=341
  _DELETEREQUESTSERVER._serialized_end=395
  _DELETEREQUEST._serialized_start=397
  _DELETEREQUEST._serialized_end=426
  _DELETERESPONSE._serialized_start=428
  _DELETERESPONSE._serialized_end=460
  _WRITEREQUESTSERVER._serialized_start=462
  _WRITEREQUESTSERVER._serialized_end=546
  _SERVER._serialized_start=549
  _SERVER._serialized_end=966
# @@protoc_insertion_point(module_scope)
